language: php

php:
  - 5.5
  - 5.6
  - nightly

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source
  - git clone https://github.com/antirez/disque.git
  - cd disque
  - make
  - src/disque-server &
  - cd ..

matrix:
  allow_failures:
    - php: nightly

script:
  - ./vendor/bin/phpunit
